//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Cases = new HashSet<Case>();
            this.Contacts = new HashSet<Contact>();
            this.Contracts = new HashSet<Contract>();
            this.Dispatches = new HashSet<Dispatch>();
            this.Dispatches1 = new HashSet<Dispatch>();
            this.Invoices = new HashSet<Invoice>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Quotes = new HashSet<Quote>();
            this.ProcurementOrders = new HashSet<ProcurementOrder>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Files = new HashSet<File>();
            this.Files1 = new HashSet<File>();
            this.FileRateTables = new HashSet<FileRateTable>();
            this.FileRateTables1 = new HashSet<FileRateTable>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Remark { get; set; }
        public string OwnerId { get; set; }
        public string Priority { get; set; }
        public Nullable<System.Guid> AccountTypeId { get; set; }
        public Nullable<System.Guid> IndustryId { get; set; }
        public Nullable<System.Guid> OwnershipId { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public Nullable<decimal> NumberOfEmployees { get; set; }
        public Nullable<decimal> NumberOfLocations { get; set; }
        public Nullable<System.Guid> RatingId { get; set; }
        public string AgreementSerialNumber { get; set; }
        public System.DateTime AgreementExpDate { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public string CustomColumn2 { get; set; }
        public string CustomColumn3 { get; set; }
        public string CustomColumn4 { get; set; }
        public string CustomColumn5 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<System.Guid> LeadId { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public Nullable<System.Guid> BillingAddressId { get; set; }
        public string BillingAddressToName { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingAddressLine3 { get; set; }
        public string BillingAddressCity { get; set; }
        public string BillingAddressPin { get; set; }
        public string BillingAddressState { get; set; }
        public string BillingAddressCountry { get; set; }
        public string BillingAddressPhone { get; set; }
        public string BillingAddressEMail { get; set; }
        public Nullable<System.Guid> ShippingAddressId { get; set; }
        public string ShippingAddressToName { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingAddressLine3 { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressPin { get; set; }
        public string ShippingAddressState { get; set; }
        public string ShippingAddressCountry { get; set; }
        public string ShippingAddressPhone { get; set; }
        public string ShippingAddressEMail { get; set; }
        public string SharedWith { get; set; }
        public bool IsSupplier { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Address Address { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Ownership Ownership { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Dispatch> Dispatches { get; set; }
        public virtual ICollection<Dispatch> Dispatches1 { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<ProcurementOrder> ProcurementOrders { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<File> Files1 { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables1 { get; set; }
    }
}
