//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.LargeDatas = new HashSet<LargeData>();
            this.LargeDatas1 = new HashSet<LargeData>();
            this.PriceBookLineItems = new HashSet<PriceBookLineItem>();
            this.PriceBookLineItems1 = new HashSet<PriceBookLineItem>();
            this.JoiningRequests = new HashSet<JoiningRequest>();
            this.JoiningRequests1 = new HashSet<JoiningRequest>();
            this.JoiningRequests2 = new HashSet<JoiningRequest>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.Quotes = new HashSet<Quote>();
            this.Quotes1 = new HashSet<Quote>();
            this.Quotes2 = new HashSet<Quote>();
            this.QuoteLineItems = new HashSet<QuoteLineItem>();
            this.QuoteLineItems1 = new HashSet<QuoteLineItem>();
            this.Contracts = new HashSet<Contract>();
            this.Contracts1 = new HashSet<Contract>();
            this.Contracts2 = new HashSet<Contract>();
            this.Contracts3 = new HashSet<Contract>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.OrderLineItems1 = new HashSet<OrderLineItem>();
            this.Organizations = new HashSet<Organization>();
            this.Organizations1 = new HashSet<Organization>();
            this.Cases = new HashSet<Case>();
            this.Cases1 = new HashSet<Case>();
            this.Cases2 = new HashSet<Case>();
            this.Cases3 = new HashSet<Case>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.InvoiceLineItems1 = new HashSet<InvoiceLineItem>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Opportunities1 = new HashSet<Opportunity>();
            this.Opportunities2 = new HashSet<Opportunity>();
            this.PriceBooks = new HashSet<PriceBook>();
            this.PriceBooks1 = new HashSet<PriceBook>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks2 = new HashSet<Task>();
            this.Tasks3 = new HashSet<Task>();
            this.Campaigns = new HashSet<Campaign>();
            this.Campaigns1 = new HashSet<Campaign>();
            this.Campaigns2 = new HashSet<Campaign>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductImages1 = new HashSet<ProductImage>();
            this.Leads = new HashSet<Lead>();
            this.Leads1 = new HashSet<Lead>();
            this.Leads2 = new HashSet<Lead>();
            this.CampaignMembers = new HashSet<CampaignMember>();
            this.CampaignMembers1 = new HashSet<CampaignMember>();
            this.ProductFamilies = new HashSet<ProductFamily>();
            this.ProductFamilies1 = new HashSet<ProductFamily>();
            this.ProductTypes = new HashSet<ProductType>();
            this.ProductTypes1 = new HashSet<ProductType>();
            this.Addresses = new HashSet<Address>();
            this.Addresses1 = new HashSet<Address>();
            this.Departments = new HashSet<Department>();
            this.Departments1 = new HashSet<Department>();
            this.Teams = new HashSet<Team>();
            this.Teams1 = new HashSet<Team>();
            this.Hierarchies = new HashSet<Hierarchy>();
            this.Invoices = new HashSet<Invoice>();
            this.Invoices1 = new HashSet<Invoice>();
            this.Invoices2 = new HashSet<Invoice>();
            this.Targets = new HashSet<Target>();
            this.Targets1 = new HashSet<Target>();
            this.Targets2 = new HashSet<Target>();
            this.EmailConfigs = new HashSet<EmailConfig>();
            this.NoticeBoards = new HashSet<NoticeBoard>();
            this.NoticeBoards1 = new HashSet<NoticeBoard>();
            this.Cases4 = new HashSet<Case>();
            this.BOMs = new HashSet<BOM>();
            this.BOMs1 = new HashSet<BOM>();
            this.BOMs2 = new HashSet<BOM>();
            this.BOMLineItems = new HashSet<BOMLineItem>();
            this.BOMLineItems1 = new HashSet<BOMLineItem>();
            this.Items = new HashSet<Item>();
            this.Items1 = new HashSet<Item>();
            this.Items2 = new HashSet<Item>();
            this.OperationBOMLineItems = new HashSet<OperationBOMLineItem>();
            this.OperationBOMLineItems1 = new HashSet<OperationBOMLineItem>();
            this.OpportunityLineItems = new HashSet<OpportunityLineItem>();
            this.OpportunityLineItems1 = new HashSet<OpportunityLineItem>();
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
            this.Dispatches = new HashSet<Dispatch>();
            this.Dispatches1 = new HashSet<Dispatch>();
            this.DispatchLineItems = new HashSet<DispatchLineItem>();
            this.DispatchLineItems1 = new HashSet<DispatchLineItem>();
            this.JobIssueHeads = new HashSet<JobIssueHead>();
            this.JobIssueHeads1 = new HashSet<JobIssueHead>();
            this.JobItemIssues = new HashSet<JobItemIssue>();
            this.JobItemIssues1 = new HashSet<JobItemIssue>();
            this.JobItemReceipts = new HashSet<JobItemReceipt>();
            this.JobItemReceipts1 = new HashSet<JobItemReceipt>();
            this.JobProductIssues = new HashSet<JobProductIssue>();
            this.JobProductReceipts = new HashSet<JobProductReceipt>();
            this.JobProductIssues1 = new HashSet<JobProductIssue>();
            this.JobProductReceipts1 = new HashSet<JobProductReceipt>();
            this.JobReceiptHeads = new HashSet<JobReceiptHead>();
            this.JobReceiptHeads1 = new HashSet<JobReceiptHead>();
            this.StockIssueHeads = new HashSet<StockIssueHead>();
            this.StockIssueHeads1 = new HashSet<StockIssueHead>();
            this.StockReceiptHeads = new HashSet<StockReceiptHead>();
            this.StockReceiptHeads1 = new HashSet<StockReceiptHead>();
            this.Operations = new HashSet<Operation>();
            this.Operations1 = new HashSet<Operation>();
            this.Processes = new HashSet<Process>();
            this.Processes1 = new HashSet<Process>();
            this.ProdPlanDetails = new HashSet<ProdPlanDetail>();
            this.ProdPlanDetails1 = new HashSet<ProdPlanDetail>();
            this.ProdPlanRawBookings = new HashSet<ProdPlanRawBooking>();
            this.ProdPlanRawBookings1 = new HashSet<ProdPlanRawBooking>();
            this.ProdPlanRawBookings2 = new HashSet<ProdPlanRawBooking>();
            this.ProcessTimeConfigs = new HashSet<ProcessTimeConfig>();
            this.ProcessTimeConfigs1 = new HashSet<ProcessTimeConfig>();
            this.Accounts = new HashSet<Account>();
            this.Accounts1 = new HashSet<Account>();
            this.Accounts2 = new HashSet<Account>();
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contact>();
            this.Contacts2 = new HashSet<Contact>();
            this.ProcurementRequestDetails = new HashSet<ProcurementRequestDetail>();
            this.ProcurementOrders = new HashSet<ProcurementOrder>();
            this.ProcurementOrderDetails = new HashSet<ProcurementOrderDetail>();
            this.ProcurementRequests = new HashSet<ProcurementRequest>();
            this.ProcurementRequestDetails1 = new HashSet<ProcurementRequestDetail>();
            this.ProcurementOrders1 = new HashSet<ProcurementOrder>();
            this.ProcurementOrderDetails1 = new HashSet<ProcurementOrderDetail>();
            this.ProcurementRequests1 = new HashSet<ProcurementRequest>();
            this.StockItemIssues = new HashSet<StockItemIssue>();
            this.StockItemReceipts = new HashSet<StockItemReceipt>();
            this.StockItemIssues1 = new HashSet<StockItemIssue>();
            this.StockItemReceipts1 = new HashSet<StockItemReceipt>();
            this.StockProductIssues = new HashSet<StockProductIssue>();
            this.StockProductReceipts = new HashSet<StockProductReceipt>();
            this.StockProductIssues1 = new HashSet<StockProductIssue>();
            this.StockProductReceipts1 = new HashSet<StockProductReceipt>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
            this.Orders3 = new HashSet<Order>();
            this.Orders4 = new HashSet<Order>();
            this.Orders5 = new HashSet<Order>();
            this.Attendances = new HashSet<Attendance>();
            this.Attendances1 = new HashSet<Attendance>();
            this.WorkMonths = new HashSet<WorkMonth>();
            this.WorkMonths1 = new HashSet<WorkMonth>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.Media = new HashSet<Media>();
            this.Media1 = new HashSet<Media>();
            this.Media2 = new HashSet<Media>();
            this.Contacts3 = new HashSet<Contact>();
            this.Files = new HashSet<File>();
            this.Files1 = new HashSet<File>();
            this.Files2 = new HashSet<File>();
            this.Files3 = new HashSet<File>();
            this.FileRateTables = new HashSet<FileRateTable>();
            this.FileRateTables1 = new HashSet<FileRateTable>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string AuthenticatedEmail { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Mobile { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.Guid> OrgId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Culture { get; set; }
        public string TimeZone { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
    
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<LargeData> LargeDatas { get; set; }
        public virtual ICollection<LargeData> LargeDatas1 { get; set; }
        public virtual ICollection<PriceBookLineItem> PriceBookLineItems { get; set; }
        public virtual ICollection<PriceBookLineItem> PriceBookLineItems1 { get; set; }
        public virtual ICollection<JoiningRequest> JoiningRequests { get; set; }
        public virtual ICollection<JoiningRequest> JoiningRequests1 { get; set; }
        public virtual ICollection<JoiningRequest> JoiningRequests2 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Quote> Quotes1 { get; set; }
        public virtual ICollection<Quote> Quotes2 { get; set; }
        public virtual ICollection<QuoteLineItem> QuoteLineItems { get; set; }
        public virtual ICollection<QuoteLineItem> QuoteLineItems1 { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Contract> Contracts1 { get; set; }
        public virtual ICollection<Contract> Contracts2 { get; set; }
        public virtual ICollection<Contract> Contracts3 { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems1 { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Organization> Organizations1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Case> Cases1 { get; set; }
        public virtual ICollection<Case> Cases2 { get; set; }
        public virtual ICollection<Case> Cases3 { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems1 { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Opportunity> Opportunities1 { get; set; }
        public virtual ICollection<Opportunity> Opportunities2 { get; set; }
        public virtual ICollection<PriceBook> PriceBooks { get; set; }
        public virtual ICollection<PriceBook> PriceBooks1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Task> Tasks2 { get; set; }
        public virtual ICollection<Task> Tasks3 { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Campaign> Campaigns1 { get; set; }
        public virtual ICollection<Campaign> Campaigns2 { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductImage> ProductImages1 { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Lead> Leads1 { get; set; }
        public virtual ICollection<Lead> Leads2 { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers1 { get; set; }
        public virtual ICollection<ProductFamily> ProductFamilies { get; set; }
        public virtual ICollection<ProductFamily> ProductFamilies1 { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual ICollection<ProductType> ProductTypes1 { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Address> Addresses1 { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Department> Departments1 { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Team> Teams1 { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies { get; set; }
        public virtual Hierarchy Hierarchy { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Invoice> Invoices1 { get; set; }
        public virtual ICollection<Invoice> Invoices2 { get; set; }
        public virtual ICollection<Target> Targets { get; set; }
        public virtual ICollection<Target> Targets1 { get; set; }
        public virtual ICollection<Target> Targets2 { get; set; }
        public virtual ICollection<EmailConfig> EmailConfigs { get; set; }
        public virtual ICollection<NoticeBoard> NoticeBoards { get; set; }
        public virtual ICollection<NoticeBoard> NoticeBoards1 { get; set; }
        public virtual ICollection<Case> Cases4 { get; set; }
        public virtual ICollection<BOM> BOMs { get; set; }
        public virtual ICollection<BOM> BOMs1 { get; set; }
        public virtual ICollection<BOM> BOMs2 { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems1 { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Item> Items1 { get; set; }
        public virtual ICollection<Item> Items2 { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems1 { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual ICollection<Dispatch> Dispatches { get; set; }
        public virtual ICollection<Dispatch> Dispatches1 { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems1 { get; set; }
        public virtual ICollection<JobIssueHead> JobIssueHeads { get; set; }
        public virtual ICollection<JobIssueHead> JobIssueHeads1 { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues1 { get; set; }
        public virtual ICollection<JobItemReceipt> JobItemReceipts { get; set; }
        public virtual ICollection<JobItemReceipt> JobItemReceipts1 { get; set; }
        public virtual ICollection<JobProductIssue> JobProductIssues { get; set; }
        public virtual ICollection<JobProductReceipt> JobProductReceipts { get; set; }
        public virtual ICollection<JobProductIssue> JobProductIssues1 { get; set; }
        public virtual ICollection<JobProductReceipt> JobProductReceipts1 { get; set; }
        public virtual ICollection<JobReceiptHead> JobReceiptHeads { get; set; }
        public virtual ICollection<JobReceiptHead> JobReceiptHeads1 { get; set; }
        public virtual ICollection<StockIssueHead> StockIssueHeads { get; set; }
        public virtual ICollection<StockIssueHead> StockIssueHeads1 { get; set; }
        public virtual ICollection<StockReceiptHead> StockReceiptHeads { get; set; }
        public virtual ICollection<StockReceiptHead> StockReceiptHeads1 { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Operation> Operations1 { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<Process> Processes1 { get; set; }
        public virtual ICollection<ProdPlanDetail> ProdPlanDetails { get; set; }
        public virtual ICollection<ProdPlanDetail> ProdPlanDetails1 { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings1 { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings2 { get; set; }
        public virtual ICollection<ProcessTimeConfig> ProcessTimeConfigs { get; set; }
        public virtual ICollection<ProcessTimeConfig> ProcessTimeConfigs1 { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Account> Accounts1 { get; set; }
        public virtual ICollection<Account> Accounts2 { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contact> Contacts1 { get; set; }
        public virtual ICollection<Contact> Contacts2 { get; set; }
        public virtual ICollection<ProcurementRequestDetail> ProcurementRequestDetails { get; set; }
        public virtual ICollection<ProcurementOrder> ProcurementOrders { get; set; }
        public virtual ICollection<ProcurementOrderDetail> ProcurementOrderDetails { get; set; }
        public virtual ICollection<ProcurementRequest> ProcurementRequests { get; set; }
        public virtual ICollection<ProcurementRequestDetail> ProcurementRequestDetails1 { get; set; }
        public virtual ICollection<ProcurementOrder> ProcurementOrders1 { get; set; }
        public virtual ICollection<ProcurementOrderDetail> ProcurementOrderDetails1 { get; set; }
        public virtual ICollection<ProcurementRequest> ProcurementRequests1 { get; set; }
        public virtual ICollection<StockItemIssue> StockItemIssues { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts { get; set; }
        public virtual ICollection<StockItemIssue> StockItemIssues1 { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts1 { get; set; }
        public virtual ICollection<StockProductIssue> StockProductIssues { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts { get; set; }
        public virtual ICollection<StockProductIssue> StockProductIssues1 { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Order> Orders2 { get; set; }
        public virtual ICollection<Order> Orders3 { get; set; }
        public virtual ICollection<Order> Orders4 { get; set; }
        public virtual ICollection<Order> Orders5 { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Attendance> Attendances1 { get; set; }
        public virtual ICollection<WorkMonth> WorkMonths { get; set; }
        public virtual ICollection<WorkMonth> WorkMonths1 { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual ICollection<Media> Media1 { get; set; }
        public virtual ICollection<Media> Media2 { get; set; }
        public virtual ICollection<Contact> Contacts3 { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<File> Files1 { get; set; }
        public virtual ICollection<File> Files2 { get; set; }
        public virtual ICollection<File> Files3 { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables1 { get; set; }
    }
}
