//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Subject { get; set; }
        public string RefNo { get; set; }
        public string Desc { get; set; }
        public string InternalComments { get; set; }
        public System.Guid PriorityId { get; set; }
        public System.Guid CaseReasonId { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public System.Guid CaseStatusId { get; set; }
        public string OwnerId { get; set; }
        public string AssignedToId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public Nullable<System.Guid> OpportunityId { get; set; }
        public Nullable<System.Guid> QuoteId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ClosingComments { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SharedWith { get; set; }
        public string ReportCompletionToId { get; set; }
        public decimal CaseNo { get; set; }
    
        public virtual AspNetUser AssignedTo { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual CaseReason CaseReason { get; set; }
        public virtual CaseStatu CaseStatu { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Opportunity Opportunity { get; set; }
        public virtual Product Product { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual AspNetUser AspNetUserReportCompletionTo { get; set; }
        public virtual Account Account { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Order Order { get; set; }
    }
}
