//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.CampaignMembers = new HashSet<CampaignMember>();
            this.Cases = new HashSet<Case>();
            this.Contracts = new HashSet<Contract>();
            this.Dispatches = new HashSet<Dispatch>();
            this.Employees = new HashSet<Employee>();
            this.Invoices = new HashSet<Invoice>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Quotes = new HashSet<Quote>();
            this.Tasks = new HashSet<Task>();
            this.Contact1 = new HashSet<Contact>();
            this.ProcurementOrders = new HashSet<ProcurementOrder>();
            this.Orders = new HashSet<Order>();
            this.Files = new HashSet<File>();
            this.FileRateTables = new HashSet<FileRateTable>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string NamePrefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string OwnerId { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public Nullable<System.Guid> ReportsTo { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEMail { get; set; }
        public string CompanyName { get; set; }
        public System.Guid LeadSourceId { get; set; }
        public bool IsProspect { get; set; }
        public bool IsEndorsement { get; set; }
        public System.Guid LevelId { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public string CustomColumn2 { get; set; }
        public string CustomColumn3 { get; set; }
        public string CustomColumn4 { get; set; }
        public string CustomColumn5 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public Nullable<System.Guid> LeadId { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public Nullable<System.Guid> MailingAddressId { get; set; }
        public string MailingAddressToName { get; set; }
        public string MailingAddressLine1 { get; set; }
        public string MailingAddressLine2 { get; set; }
        public string MailingAddressLine3 { get; set; }
        public string MailingAddressCity { get; set; }
        public string MailingAddressPin { get; set; }
        public string MailingAddressState { get; set; }
        public string MailingAddressCountry { get; set; }
        public string MailingAddressPhone { get; set; }
        public string MailingAddressEMail { get; set; }
        public Nullable<System.Guid> OtherAddressId { get; set; }
        public string OtherAddressToName { get; set; }
        public string OtherAddressLine1 { get; set; }
        public string OtherAddressLine2 { get; set; }
        public string OtherAddressLine3 { get; set; }
        public string OtherAddressCity { get; set; }
        public string OtherAddressPin { get; set; }
        public string OtherAddressState { get; set; }
        public string OtherAddressCountry { get; set; }
        public string OtherAddressPhone { get; set; }
        public string OtherAddressEMail { get; set; }
        public string SharedWith { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public bool IsEmployee { get; set; }
        public string PreferredOwnerId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual LeadSource LeadSource { get; set; }
        public virtual Level Level { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Dispatch> Dispatches { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        public virtual ICollection<ProcurementOrder> ProcurementOrders { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables { get; set; }
    }
}
