//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostingGroup
    {
        public CostingGroup()
        {
            this.CostingSubGroups = new HashSet<CostingSubGroup>();
            this.Items = new HashSet<Item>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
    
        public virtual ICollection<CostingSubGroup> CostingSubGroups { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
