//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Teams = new HashSet<Team>();
            this.Hierarchies = new HashSet<Hierarchy>();
            this.Employees = new HashSet<Employee>();
            this.EnterpriseStages = new HashSet<EnterpriseStage>();
            this.ProcurementRequests = new HashSet<ProcurementRequest>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EnterpriseStage> EnterpriseStages { get; set; }
        public virtual ICollection<ProcurementRequest> ProcurementRequests { get; set; }
    }
}
