//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public Dispatch()
        {
            this.DispatchLineItems = new HashSet<DispatchLineItem>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string RefNo { get; set; }
        public System.DateTime Date { get; set; }
        public string MarketType { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid SubAccountId { get; set; }
        public System.Guid ContactId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public string Notify { get; set; }
        public string Consignee { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public System.Guid DeliveryStatusId { get; set; }
        public string DeliveryTerms { get; set; }
        public string PaymentTerms { get; set; }
        public string SpecialTerms { get; set; }
        public string Remark { get; set; }
        public string SharedWith { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<decimal> LineItemsAmount { get; set; }
        public Nullable<decimal> LineItemsQuantity { get; set; }
        public string Dispatcher { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems { get; set; }
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Order Order { get; set; }
    }
}
