//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string SmtpUsername { get; set; }
        public string SmtpPassword { get; set; }
        public string SmtpHost { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public string Pop3Username { get; set; }
        public string Pop3Password { get; set; }
        public string Pop3Host { get; set; }
        public Nullable<int> Pop3Port { get; set; }
        public bool Ssl { get; set; }
        public bool Tls { get; set; }
        public string HeskSettings { get; set; }
        public string OtherSettings { get; set; }
        public System.Guid OrgId { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
