//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseStage
    {
        public EnterpriseStage()
        {
            this.Operations = new HashSet<Operation>();
            this.Processes = new HashSet<Process>();
            this.StockIssueHeads = new HashSet<StockIssueHead>();
            this.StockIssueHeads1 = new HashSet<StockIssueHead>();
            this.StockReceiptHeads = new HashSet<StockReceiptHead>();
            this.StockReceiptHeads1 = new HashSet<StockReceiptHead>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string Type { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<StockIssueHead> StockIssueHeads { get; set; }
        public virtual ICollection<StockIssueHead> StockIssueHeads1 { get; set; }
        public virtual ICollection<StockReceiptHead> StockReceiptHeads { get; set; }
        public virtual ICollection<StockReceiptHead> StockReceiptHeads1 { get; set; }
    }
}
