//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public string UserId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public System.Guid TeamId { get; set; }
        public string ReportsTo { get; set; }
        public string Designation { get; set; }
        public System.Guid OrgId { get; set; }
    
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Department Department { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Team Team { get; set; }
    }
}
