//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Cases = new HashSet<Case>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string RefNo { get; set; }
        public string OwnerId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public Nullable<System.Guid> OpportunityId { get; set; }
        public Nullable<System.Guid> QuoteId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public System.Guid InvoiceStatusId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string PaymentReceiptDetails { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<System.Guid> BillingAddressId { get; set; }
        public string BillingAddressToName { get; set; }
        public string BillingAddressLine1 { get; set; }
        public string BillingAddressLine2 { get; set; }
        public string BillingAddressLine3 { get; set; }
        public string BillingAddressCity { get; set; }
        public string BillingAddressPin { get; set; }
        public string BillingAddressState { get; set; }
        public string BillingAddressCountry { get; set; }
        public string BillingAddressPhone { get; set; }
        public Nullable<System.Guid> ShippingAddressId { get; set; }
        public string ShippingAddressToName { get; set; }
        public string ShippingAddressLine1 { get; set; }
        public string ShippingAddressLine2 { get; set; }
        public string ShippingAddressLine3 { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressPin { get; set; }
        public string ShippingAddressState { get; set; }
        public string ShippingAddressCountry { get; set; }
        public string ShippingAddressPhone { get; set; }
        public string PaymentTerms { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<decimal> LineItemsAmount { get; set; }
        public Nullable<decimal> PostTaxAmount { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> LineItemsQuantity { get; set; }
        public string SharedWith { get; set; }
        public string Remark { get; set; }
        public decimal InvoiceNo { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual InvoiceStatu InvoiceStatu { get; set; }
        public virtual Opportunity Opportunity { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual Account Account { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Order Order { get; set; }
    }
}
