//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.BOMLineItems = new HashSet<BOMLineItem>();
            this.JobItemIssues = new HashSet<JobItemIssue>();
            this.JobItemReceipts = new HashSet<JobItemReceipt>();
            this.ProdPlanRawBookings = new HashSet<ProdPlanRawBooking>();
            this.ProcurementRequestDetails = new HashSet<ProcurementRequestDetail>();
            this.ProcurementOrderDetails = new HashSet<ProcurementOrderDetail>();
            this.StockItemIssues = new HashSet<StockItemIssue>();
            this.StockItemReceipts = new HashSet<StockItemReceipt>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Desc { get; set; }
        public string OwnerId { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> QuantityPerLot { get; set; }
        public Nullable<decimal> LotWeight { get; set; }
        public Nullable<System.Guid> LotWeightUnitId { get; set; }
        public string ABCClass { get; set; }
        public string VEDClass { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public Nullable<decimal> MinStkLvl { get; set; }
        public Nullable<decimal> SafetyQty { get; set; }
        public Nullable<decimal> ReOrdrQty { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public Nullable<decimal> OpeningLotCost { get; set; }
        public Nullable<decimal> Wastage { get; set; }
        public Nullable<decimal> ScrapRate { get; set; }
        public Nullable<decimal> Gauge { get; set; }
        public Nullable<decimal> Level { get; set; }
        public Nullable<System.Guid> AlternativeId { get; set; }
        public Nullable<System.Guid> ClassificationId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public Nullable<System.Guid> StyleId { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> SubGroupId { get; set; }
        public Nullable<System.Guid> CostingGroupId { get; set; }
        public Nullable<System.Guid> CostingSubGroupId { get; set; }
        public Nullable<System.Guid> NatureId { get; set; }
        public Nullable<System.Guid> ShapeId { get; set; }
        public Nullable<System.Guid> ColourId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual CostingGroup CostingGroup { get; set; }
        public virtual CostingSubGroup CostingSubGroup { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemClassification ItemClassification { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual WeightUnit WeightUnit { get; set; }
        public virtual Nature Nature { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Shape Shape { get; set; }
        public virtual Style Style { get; set; }
        public virtual ItemSubGroup ItemSubGroup { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues { get; set; }
        public virtual ICollection<JobItemReceipt> JobItemReceipts { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings { get; set; }
        public virtual ICollection<ProcurementRequestDetail> ProcurementRequestDetails { get; set; }
        public virtual ICollection<ProcurementOrderDetail> ProcurementOrderDetails { get; set; }
        public virtual ICollection<StockItemIssue> StockItemIssues { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts { get; set; }
    }
}
