//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobIssueHead
    {
        public JobIssueHead()
        {
            this.JobItemIssues = new HashSet<JobItemIssue>();
            this.JobProductIssues = new HashSet<JobProductIssue>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string RefNo { get; set; }
        public string JobType { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid IssuedByProcessId { get; set; }
        public System.Guid IssuedToProcessId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Remark { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues { get; set; }
        public virtual ICollection<JobProductIssue> JobProductIssues { get; set; }
        public virtual Process Process { get; set; }
        public virtual Process Process1 { get; set; }
    }
}
