//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadSource
    {
        public LeadSource()
        {
            this.Opportunities = new HashSet<Opportunity>();
            this.Leads = new HashSet<Lead>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public Nullable<bool> Authorized { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
