//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public Lead()
        {
            this.Opportunities = new HashSet<Opportunity>();
            this.Tasks = new HashSet<Task>();
            this.CampaignMembers = new HashSet<CampaignMember>();
            this.Accounts = new HashSet<Account>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Desc { get; set; }
        public string OwnerId { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEMail { get; set; }
        public string CompanyName { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> AnnualRevenue { get; set; }
        public Nullable<decimal> NumberOfEmployees { get; set; }
        public System.Guid LeadSourceId { get; set; }
        public System.Guid LeadStatusId { get; set; }
        public Nullable<System.Guid> RatingId { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public string CustomColumn2 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public bool IsConverted { get; set; }
        public byte[] TimeStamp { get; set; }
        public string AddressToName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressCity { get; set; }
        public string AddressPin { get; set; }
        public string AddressState { get; set; }
        public string AddressCountry { get; set; }
        public string AddressPhone { get; set; }
        public string AddressEMail { get; set; }
        public string SharedWith { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual LeadSource LeadSource { get; set; }
        public virtual LeadStatu LeadStatu { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
