//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.OperationBOMLineItems = new HashSet<OperationBOMLineItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid EnterpriseStageId { get; set; }
        public System.Guid ProcessId { get; set; }
        public Nullable<int> Serial { get; set; }
        public string ShrtDesc { get; set; }
        public Nullable<decimal> LabourRatePerHour { get; set; }
        public Nullable<decimal> DepreciationRatePerHour { get; set; }
        public Nullable<decimal> EnergyRatePerHour { get; set; }
        public Nullable<decimal> OverheadRatePerHour { get; set; }
        public Nullable<decimal> OtherDirectExpensesRatePerHour { get; set; }
        public Nullable<decimal> OtherInDirectExpensesRatePerHour { get; set; }
        public Nullable<decimal> RatePerHour { get; set; }
        public decimal CycleTimeInHour { get; set; }
        public string Remark { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public byte[] TimeStamp { get; set; }
        public decimal CycleCapacity { get; set; }
        public Nullable<decimal> QuantityPerHour { get; set; }
        public Nullable<decimal> PerUnitCost { get; set; }
        public string Type { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual EnterpriseStage EnterpriseStage { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Process Process { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems { get; set; }
    }
}
