//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Contracts = new HashSet<Contract>();
            this.LargeDatas = new HashSet<LargeData>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.PriceBookLineItems = new HashSet<PriceBookLineItem>();
            this.Quotes = new HashSet<Quote>();
            this.QuoteLineItems = new HashSet<QuoteLineItem>();
            this.Cases = new HashSet<Case>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.Opportunities = new HashSet<Opportunity>();
            this.PriceBooks = new HashSet<PriceBook>();
            this.Products = new HashSet<Product>();
            this.Tasks = new HashSet<Task>();
            this.Campaigns = new HashSet<Campaign>();
            this.ProductImages = new HashSet<ProductImage>();
            this.Leads = new HashSet<Lead>();
            this.CampaignMembers = new HashSet<CampaignMember>();
            this.ProductFamilies = new HashSet<ProductFamily>();
            this.ProductTypes = new HashSet<ProductType>();
            this.Addresses = new HashSet<Address>();
            this.Departments = new HashSet<Department>();
            this.Teams = new HashSet<Team>();
            this.Hierarchies = new HashSet<Hierarchy>();
            this.Invoices = new HashSet<Invoice>();
            this.Targets = new HashSet<Target>();
            this.EmailConfigs = new HashSet<EmailConfig>();
            this.NoticeBoards = new HashSet<NoticeBoard>();
            this.BOMs = new HashSet<BOM>();
            this.BOMLineItems = new HashSet<BOMLineItem>();
            this.Items = new HashSet<Item>();
            this.OperationBOMLineItems = new HashSet<OperationBOMLineItem>();
            this.OpportunityLineItems = new HashSet<OpportunityLineItem>();
            this.Employees = new HashSet<Employee>();
            this.Dispatches = new HashSet<Dispatch>();
            this.DispatchLineItems = new HashSet<DispatchLineItem>();
            this.JobIssueHeads = new HashSet<JobIssueHead>();
            this.JobItemIssues = new HashSet<JobItemIssue>();
            this.JobItemReceipts = new HashSet<JobItemReceipt>();
            this.JobProductIssues = new HashSet<JobProductIssue>();
            this.JobProductReceipts = new HashSet<JobProductReceipt>();
            this.JobReceiptHeads = new HashSet<JobReceiptHead>();
            this.StockIssueHeads = new HashSet<StockIssueHead>();
            this.StockReceiptHeads = new HashSet<StockReceiptHead>();
            this.Operations = new HashSet<Operation>();
            this.Processes = new HashSet<Process>();
            this.ProdPlanDetails = new HashSet<ProdPlanDetail>();
            this.ProdPlanRawBookings = new HashSet<ProdPlanRawBooking>();
            this.ProcessTimeConfigs = new HashSet<ProcessTimeConfig>();
            this.Accounts = new HashSet<Account>();
            this.Contacts = new HashSet<Contact>();
            this.ProcurementRequestDetails = new HashSet<ProcurementRequestDetail>();
            this.ProcurementOrders = new HashSet<ProcurementOrder>();
            this.ProcurementOrderDetails = new HashSet<ProcurementOrderDetail>();
            this.ProcurementRequests = new HashSet<ProcurementRequest>();
            this.StockItemIssues = new HashSet<StockItemIssue>();
            this.StockItemReceipts = new HashSet<StockItemReceipt>();
            this.StockProductIssues = new HashSet<StockProductIssue>();
            this.StockProductReceipts = new HashSet<StockProductReceipt>();
            this.Orders = new HashSet<Order>();
            this.Attendances = new HashSet<Attendance>();
            this.WorkMonths = new HashSet<WorkMonth>();
            this.Media = new HashSet<Media>();
            this.Files = new HashSet<File>();
            this.FileRateTables = new HashSet<FileRateTable>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShortName { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string ApproverEMail { get; set; }
        public string ApproverPhone { get; set; }
        public string TIN { get; set; }
        public string RegistrationNumber { get; set; }
        public byte[] Logo { get; set; }
        public byte[] Trademark { get; set; }
        public string ImagePath { get; set; }
        public string ExportLicense { get; set; }
        public string ImportLicense { get; set; }
        public string Website { get; set; }
        public string ServiceURI { get; set; }
        public string FAX { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public string CustomColumn2 { get; set; }
        public string Slogan { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<LargeData> LargeDatas { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<PriceBookLineItem> PriceBookLineItems { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<QuoteLineItem> QuoteLineItems { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<PriceBook> PriceBooks { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<CampaignMember> CampaignMembers { get; set; }
        public virtual ICollection<ProductFamily> ProductFamilies { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Target> Targets { get; set; }
        public virtual ICollection<EmailConfig> EmailConfigs { get; set; }
        public virtual ICollection<NoticeBoard> NoticeBoards { get; set; }
        public virtual ICollection<BOM> BOMs { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Dispatch> Dispatches { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems { get; set; }
        public virtual ICollection<JobIssueHead> JobIssueHeads { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues { get; set; }
        public virtual ICollection<JobItemReceipt> JobItemReceipts { get; set; }
        public virtual ICollection<JobProductIssue> JobProductIssues { get; set; }
        public virtual ICollection<JobProductReceipt> JobProductReceipts { get; set; }
        public virtual ICollection<JobReceiptHead> JobReceiptHeads { get; set; }
        public virtual ICollection<StockIssueHead> StockIssueHeads { get; set; }
        public virtual ICollection<StockReceiptHead> StockReceiptHeads { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<ProdPlanDetail> ProdPlanDetails { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings { get; set; }
        public virtual ICollection<ProcessTimeConfig> ProcessTimeConfigs { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<ProcurementRequestDetail> ProcurementRequestDetails { get; set; }
        public virtual ICollection<ProcurementOrder> ProcurementOrders { get; set; }
        public virtual ICollection<ProcurementOrderDetail> ProcurementOrderDetails { get; set; }
        public virtual ICollection<ProcurementRequest> ProcurementRequests { get; set; }
        public virtual ICollection<StockItemIssue> StockItemIssues { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts { get; set; }
        public virtual ICollection<StockProductIssue> StockProductIssues { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<WorkMonth> WorkMonths { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<FileRateTable> FileRateTables { get; set; }
    }
}
