//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceBookLineItem
    {
        public PriceBookLineItem()
        {
            this.QuoteLineItems = new HashSet<QuoteLineItem>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.OpportunityLineItems = new HashSet<OpportunityLineItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PriceBookId { get; set; }
        public System.Guid ProductId { get; set; }
        public decimal ListPrice { get; set; }
        public string ShrtDesc { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<QuoteLineItem> QuoteLineItems { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual PriceBook PriceBook { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems { get; set; }
    }
}
