//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority
    {
        public Priority()
        {
            this.Cases = new HashSet<Case>();
            this.Tasks = new HashSet<Task>();
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Serial { get; set; }
    
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
