//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdPlanDetail
    {
        public ProdPlanDetail()
        {
            this.ProdPlanRawBookings = new HashSet<ProdPlanRawBooking>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid ProcessId { get; set; }
        public Nullable<int> Serial { get; set; }
        public System.Guid OrderLineItemId { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid PriceBookId { get; set; }
        public System.Guid ProductId { get; set; }
        public decimal JobNo { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.Guid> WeightUnitId { get; set; }
        public decimal CycleTimeInHour { get; set; }
        public decimal CycleCapacity { get; set; }
        public Nullable<decimal> QuantityPerHour { get; set; }
        public string JobType { get; set; }
        public decimal SetupTimeInHrs { get; set; }
        public decimal AddOnTimeInHrs { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public System.DateTime ActualStartDateTime { get; set; }
        public System.DateTime ActualEndDateTime { get; set; }
        public string Remark { get; set; }
        public bool IsRawBookingDone { get; set; }
        public bool IsIssuedForProduction { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual OrderLineItem OrderLineItem { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual PriceBook PriceBook { get; set; }
        public virtual Process Process { get; set; }
        public virtual Product Product { get; set; }
        public virtual WeightUnit WeightUnit { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings { get; set; }
        public virtual Order Order { get; set; }
    }
}
