//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Cases = new HashSet<Case>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.PriceBookLineItems = new HashSet<PriceBookLineItem>();
            this.QuoteLineItems = new HashSet<QuoteLineItem>();
            this.ProductImages = new HashSet<ProductImage>();
            this.OpportunityLineItems = new HashSet<OpportunityLineItem>();
            this.DispatchLineItems = new HashSet<DispatchLineItem>();
            this.Operations = new HashSet<Operation>();
            this.ProdPlanDetails = new HashSet<ProdPlanDetail>();
            this.StockProductIssues = new HashSet<StockProductIssue>();
            this.StockProductReceipts = new HashSet<StockProductReceipt>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Desc { get; set; }
        public System.Guid ProductFamilyId { get; set; }
        public System.Guid ProductTypeId { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public string CustomColumn2 { get; set; }
        public string CustomColumn3 { get; set; }
        public string CustomColumn4 { get; set; }
        public string CustomColumn5 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public string SharedWith { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.Guid> WeightUnitId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<PriceBookLineItem> PriceBookLineItems { get; set; }
        public virtual ICollection<QuoteLineItem> QuoteLineItems { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ProductFamily ProductFamily { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual WeightUnit WeightUnit { get; set; }
        public virtual BOM BOM { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<ProdPlanDetail> ProdPlanDetails { get; set; }
        public virtual ICollection<StockProductIssue> StockProductIssues { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts { get; set; }
    }
}
