//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReceiptHead
    {
        public StockReceiptHead()
        {
            this.StockItemReceipts = new HashSet<StockItemReceipt>();
            this.StockProductReceipts = new HashSet<StockProductReceipt>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string RefNo { get; set; }
        public string JobType { get; set; }
        public System.Guid ReceiptByEnterpriseStageId { get; set; }
        public System.Guid ReceiptByProcessId { get; set; }
        public System.Guid ReceiptFromEnterpriseStageId { get; set; }
        public System.Guid ReceiptFromProcessId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Remark { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> ProcurementOrderId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual EnterpriseStage EnterpriseStage { get; set; }
        public virtual EnterpriseStage EnterpriseStage1 { get; set; }
        public virtual Process Process { get; set; }
        public virtual Process Process1 { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts { get; set; }
        public virtual ProcurementOrder ProcurementOrder { get; set; }
        public virtual Order Order { get; set; }
    }
}
