//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public string Desc { get; set; }
        public string OwnerId { get; set; }
        public Nullable<System.Guid> LeadId { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public string RelatedToObjectName { get; set; }
        public Nullable<System.Guid> RelatedToId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsAllDay { get; set; }
        public System.Guid TaskStatusId { get; set; }
        public System.Guid PriorityId { get; set; }
        public System.DateTime Reminder { get; set; }
        public string ReportCompletionToId { get; set; }
        public System.Guid OrgId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public string CustomColumn1 { get; set; }
        public Nullable<System.Guid> ColExtensionId { get; set; }
        public Nullable<decimal> ProgressPercent { get; set; }
        public string ProgressDesc { get; set; }
        public byte[] TimeStamp { get; set; }
        public string SharedWith { get; set; }
        public decimal TaskNo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUserReportCompletionTo { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual Lead Lead { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
