//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifetrons.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightUnit
    {
        public WeightUnit()
        {
            this.QuoteLineItems = new HashSet<QuoteLineItem>();
            this.OrderLineItems = new HashSet<OrderLineItem>();
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
            this.Products = new HashSet<Product>();
            this.BOMs = new HashSet<BOM>();
            this.BOMLineItems = new HashSet<BOMLineItem>();
            this.BOMLineItems1 = new HashSet<BOMLineItem>();
            this.Items = new HashSet<Item>();
            this.OperationBOMLineItems = new HashSet<OperationBOMLineItem>();
            this.OperationBOMLineItems1 = new HashSet<OperationBOMLineItem>();
            this.OpportunityLineItems = new HashSet<OpportunityLineItem>();
            this.OrderLineItems1 = new HashSet<OrderLineItem>();
            this.DispatchLineItems = new HashSet<DispatchLineItem>();
            this.JobItemIssues = new HashSet<JobItemIssue>();
            this.JobItemReceipts = new HashSet<JobItemReceipt>();
            this.JobProductIssues = new HashSet<JobProductIssue>();
            this.JobProductReceipts = new HashSet<JobProductReceipt>();
            this.ProdPlanDetails = new HashSet<ProdPlanDetail>();
            this.ProdPlanRawBookings = new HashSet<ProdPlanRawBooking>();
            this.ProcurementOrderDetails = new HashSet<ProcurementOrderDetail>();
            this.ProcurementRequestDetails = new HashSet<ProcurementRequestDetail>();
            this.StockItemIssues = new HashSet<StockItemIssue>();
            this.StockItemReceipts = new HashSet<StockItemReceipt>();
            this.StockProductIssues = new HashSet<StockProductIssue>();
            this.StockProductReceipts = new HashSet<StockProductReceipt>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShrtDesc { get; set; }
        public bool Authorized { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Serial { get; set; }
    
        public virtual ICollection<QuoteLineItem> QuoteLineItems { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<BOM> BOMs { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems { get; set; }
        public virtual ICollection<BOMLineItem> BOMLineItems1 { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems { get; set; }
        public virtual ICollection<OperationBOMLineItem> OperationBOMLineItems1 { get; set; }
        public virtual ICollection<OpportunityLineItem> OpportunityLineItems { get; set; }
        public virtual ICollection<OrderLineItem> OrderLineItems1 { get; set; }
        public virtual ICollection<DispatchLineItem> DispatchLineItems { get; set; }
        public virtual ICollection<JobItemIssue> JobItemIssues { get; set; }
        public virtual ICollection<JobItemReceipt> JobItemReceipts { get; set; }
        public virtual ICollection<JobProductIssue> JobProductIssues { get; set; }
        public virtual ICollection<JobProductReceipt> JobProductReceipts { get; set; }
        public virtual ICollection<ProdPlanDetail> ProdPlanDetails { get; set; }
        public virtual ICollection<ProdPlanRawBooking> ProdPlanRawBookings { get; set; }
        public virtual ICollection<ProcurementOrderDetail> ProcurementOrderDetails { get; set; }
        public virtual ICollection<ProcurementRequestDetail> ProcurementRequestDetails { get; set; }
        public virtual ICollection<StockItemIssue> StockItemIssues { get; set; }
        public virtual ICollection<StockItemReceipt> StockItemReceipts { get; set; }
        public virtual ICollection<StockProductIssue> StockProductIssues { get; set; }
        public virtual ICollection<StockProductReceipt> StockProductReceipts { get; set; }
    }
}
