USE [master]
GO

/****** Object:  Database [LtSysDb1]    Script Date: 10/03/2015 12:29:24 PM ******/
CREATE DATABASE [LtSysDb1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LtSysDb1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LtSysDb1.mdf' , SIZE = 13312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [LARGE] 
( NAME = N'LtSysDb1_Large', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LtSysDb1Large.ndf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LtSysDb1_Large_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LtSysDb1Large_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LtSysDb1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LtSysDb1_log.ldf' , SIZE = 29504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LtSysDb1] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LtSysDb1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LtSysDb1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LtSysDb1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LtSysDb1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LtSysDb1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LtSysDb1] SET ARITHABORT OFF 
GO

ALTER DATABASE [LtSysDb1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LtSysDb1] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LtSysDb1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LtSysDb1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LtSysDb1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LtSysDb1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LtSysDb1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LtSysDb1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LtSysDb1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LtSysDb1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LtSysDb1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LtSysDb1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LtSysDb1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LtSysDb1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LtSysDb1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LtSysDb1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LtSysDb1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LtSysDb1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LtSysDb1] SET RECOVERY FULL 
GO

ALTER DATABASE [LtSysDb1] SET  MULTI_USER 
GO

ALTER DATABASE [LtSysDb1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LtSysDb1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LtSysDb1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LtSysDb1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LtSysDb1] SET  READ_WRITE 
GO


